# Generated by Django 6.0.2 on 2026-02-25 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_idea', models.TextField()),
                ('problem_statement', models.TextField()),
                ('features', models.TextField()),
                ('user_stories', models.TextField()),
                ('tech_stack', models.TextField()),
                ('risks', models.TextField()),
                ('mvp_scope', models.TextField()),
                ('future_scope', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
