# Generated by Django 6.0.2 on 2026-02-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_requirementanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementanalysis',
            name='risk_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
